import compileall

print "This may take a while!"

compileall.compile_dir(".", force=1)

## This may take a while!
## Listing . ...
## Compiling .\SimpleAsyncHTTP.py ...
## Compiling .\aifc-example-1.py ...
## Compiling .\anydbm-example-1.py ...
## ...
